[[items]]
description = """
## 業務を最適化する、本質を見極めたアプリ設計・提案

本当に必要なシステムの形とはどのようなものか。
ヒアリングや各作業工程でのお打ち合わせを通して、シンプルで本質的なアプリの設計方針・アドバイスおよび
モダンな開発ガイドラインの策定を一緒に創造していきます。
"""
heading = "伴走スタイルの Web アプリ開発"
image = "/img/aoi.png"
