backend:
  name: git-gateway
  branch: master
display_url: https://tagbangers.co.jp
media_folder: public/img
public_folder: img
publish_mode: editorial_workflow

collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/blog'
    create: true
    identifier_field: name
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'contents'
    label: 'Contents'
    files:
      - label: 'Services'
        name: 'services'
        file: 'content/services.yml'
        fields:
          - label: 'Service'
            name: 'service'
            widget: list
            fields:
              - { label: 'Heading', name: 'heading', widget: 'string' }
              - {
                  label: 'Description',
                  name: 'description',
                  widget: 'markdown',
                }
              - { label: 'Image', name: 'image', widget: 'image' }

      - label: 'Clients'
        name: 'clients'
        file: 'content/clients.toml'
        format: 'toml'
        fields:
          - label: 'Client'
            name: 'client'
            widget: list
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Slug', name: 'slug', widget: 'string' }
              - { label: 'Logo', name: 'logo', widget: 'image' }
